/**
 * Unit tests for report generation: markdown report, console summary,
 * and report persistence (exercised against a throwaway temp directory).
 */
import { test, expect } from "@playwright/test";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { generateReport, saveReport, consoleSummary } from "../src/reporter.js";
import type { ScanResult } from "../src/types.js";
import { makeBug, makeFlow, makeFlowMap, makePage, makeResult, makeStats } from "./helpers.js";

function richResult(): ScanResult {
  const flowMap = makeFlowMap(
    "https://s.io",
    [
      makePage("https://s.io/", { title: "Home" }),
      makePage("https://s.io/broken", { title: "[ERROR] net::ERR_TIMED_OUT" }),
    ],
    {
      edges: [{ from: "https://s.io/", to: "https://s.io/broken", label: "link" }],
      flows: [
        makeFlow({
          name: "Form submission on Home",
          steps: [
            { action: "navigate", target: "https://s.io/", pageUrl: "https://s.io/", description: "Go home" },
          ],
          generatedSpec: "// generated spec placeholder",
        }),
      ],
    }
  );

  // Deliberately ordered low-severity first to prove the report sorts.
  const bugs = [
    makeBug({ id: "BUG-LOW1", severity: "low", title: "Low finding", url: "https://s.io/" }),
    makeBug({
      id: "BUG-CRIT1",
      severity: "critical",
      title: "Critical finding",
      url: "https://s.io/",
      evidence: "stack trace here",
      reproduction: ["Open the page", "Click the button"],
    }),
    makeBug({ id: "BUG-HIGH1", severity: "high", title: "High finding", url: "https://s.io/", location: "#hero" }),
  ];

  return makeResult({
    flowMap,
    bugs,
    generatedTests: [
      makeFlow({ name: "Passing test", steps: [], generatedSpec: "// spec", specPasses: true }),
      makeFlow({ name: "Failing test", steps: [], generatedSpec: "// spec", specPasses: false }),
    ],
    stats: makeStats({
      pagesCrawled: 2,
      bugsFound: 3,
      flowsDiscovered: 1,
      testsGenerated: 2,
      durationMs: 12_500,
    }),
    reportPath: "out/report.md",
  });
}

test.describe("generateReport", () => {
  test("renders header, summary table, and footer", () => {
    const md = generateReport(richResult());
    expect(md).toContain("# 🐛 BugScout Report — https://s.io");
    expect(md).toContain("| Target URL | https://s.io |");
    expect(md).toContain("| Pages crawled | 2 |");
    expect(md).toContain("| Bugs found | 3 |");
    expect(md).toContain("| Flows discovered | 1 |");
    expect(md).toContain("| Tests generated | 2 |");
    expect(md).toContain("| Duration | 12.5s |");
    expect(md).toContain("*Report generated by [BugScout](https://github.com/mhmdtaha091/bugscout) v0.1.0*");
  });

  test("breaks down findings by severity", () => {
    const md = generateReport(richResult());
    expect(md).toContain("### Severity Breakdown");
    expect(md).toContain("| 🔴 critical | 1 |");
    expect(md).toContain("| 🟠 high | 1 |");
    expect(md).toContain("| 🟢 low | 1 |");
  });

  test("sorts bug findings by severity, critical first", () => {
    const md = generateReport(richResult());
    const crit = md.indexOf("BUG-CRIT1: Critical finding");
    const high = md.indexOf("BUG-HIGH1: High finding");
    const low = md.indexOf("BUG-LOW1: Low finding");
    expect(crit).toBeGreaterThan(-1);
    expect(high).toBeGreaterThan(crit);
    expect(low).toBeGreaterThan(high);
  });

  test("renders evidence, reproduction steps, and location for findings", () => {
    const md = generateReport(richResult());
    expect(md).toContain("stack trace here");
    expect(md).toContain("1. Open the page");
    expect(md).toContain("1. Click the button");
    expect(md).toContain("- **Location:** `#hero`");
  });

  test("marks pages that failed to crawl in the site map", () => {
    const md = generateReport(richResult());
    expect(md).toContain("Discovered **2 pages** and **1 links**");
    expect(md).toContain("⚠️ [ERROR] net::ERR_TIMED_OUT");
  });

  test("embeds discovered flows and their generated specs", () => {
    const md = generateReport(richResult());
    expect(md).toContain("## 🔄 Discovered User Flows");
    expect(md).toContain("### Form submission on Home");
    expect(md).toContain("// generated spec placeholder");
  });

  test("shows pass/fail status for generated tests", () => {
    const md = generateReport(richResult());
    expect(md).toContain("## 🧪 Generated Playwright Tests");
    expect(md).toContain("- **Status:** ✅ Passing");
    expect(md).toContain("- **Status:** ❌ Failing");
  });

  test("celebrates a clean scan instead of showing an empty findings section", () => {
    const md = generateReport(makeResult());
    expect(md).toContain("## 🎉 No bugs detected!");
    expect(md).not.toContain("## 🐞 Bug Findings");
    expect(md).not.toContain("### Severity Breakdown");
  });

  test("only mentions LLM cost when LLM calls were made", () => {
    const noLlm = generateReport(richResult());
    expect(noLlm).not.toContain("| LLM calls |");
    expect(noLlm).not.toContain("> Total cost:");

    const withLlm = makeResult({
      stats: makeStats({
        llmCalls: [
          { model: "m", prompt: "p", response: "r", tokensIn: 10, tokensOut: 5, cost: 0.1234, latencyMs: 100 },
        ],
        totalCost: 0.1234,
      }),
    });
    const md = generateReport(withLlm);
    expect(md).toContain("| LLM calls | 1 |");
    expect(md).toContain("| Total LLM cost | $0.1234 |");
    expect(md).toContain("> Total cost: $0.1234");
  });
});

test.describe("consoleSummary", () => {
  test("summarizes counts and points at the report", () => {
    const result = richResult();
    result.reportPath = "out/report.md";
    const summary = consoleSummary(result);
    expect(summary).toContain("BugScout Scan Complete");
    expect(summary).toContain("Pages crawled:   2");
    expect(summary).toContain("Bugs found:      3");
    expect(summary).toContain("📄 Full report: out/report.md");
  });

  test("only prints severity lines for severities that occurred", () => {
    const summary = consoleSummary(richResult());
    expect(summary).toContain("🔴 Critical: 1");
    expect(summary).toContain("🟠 High:     1");
    expect(summary).toContain("🟢 Low:      1");
    expect(summary).not.toContain("🟡 Medium:");
  });

  test("only prints the cost line when something was spent", () => {
    expect(consoleSummary(richResult())).not.toContain("Cost:");
    const paid = makeResult({ stats: makeStats({ totalCost: 0.05 }) });
    expect(consoleSummary(paid)).toContain("$0.0500");
  });
});

test.describe("saveReport", () => {
  test("writes report.md plus a screenshots dir and returns the path", () => {
    const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "bugscout-test-"));
    try {
      const outputDir = path.join(tmp, "nested", "run-1");
      const reportPath = saveReport(richResult(), outputDir);

      expect(reportPath).toBe(path.join(outputDir, "report.md"));
      expect(fs.existsSync(reportPath)).toBe(true);
      expect(fs.existsSync(path.join(outputDir, "screenshots"))).toBe(true);

      const content = fs.readFileSync(reportPath, "utf-8");
      expect(content.startsWith("# 🐛 BugScout Report — https://s.io")).toBe(true);
    } finally {
      fs.rmSync(tmp, { recursive: true, force: true });
    }
  });
});
