/**
 * CI integration — GitHub Action and regression mode.
 * v3 per WEBQA_AGENT_PLAN.md.
 *
 * CI mode:
 * - Run on PR preview deployments, comment findings on the PR
 * - Regression mode: re-run generated suite on each release, diff results
 *
 * Security extension stub (bridges to PentestAI):
 * - Authenticated-flow fuzzing
 * - IDOR probing on discovered endpoints
 * - Gated behind "authorized targets only" flag
 */

import type { ScanResult, BugFinding } from "./types.js";

export interface CIConfig {
  /** GitHub token for PR comments */
  githubToken?: string;
  /** Repository in owner/repo format */
  repository?: string;
  /** PR number to comment on */
  prNumber?: number;
  /** Whether to fail the CI run on findings */
  failOn?: "critical" | "high" | "medium" | "never";
  /** Baseline scan result for regression comparison */
  baseline?: ScanResult;
  /** Enable security fuzzing (authorized targets only) */
  securityFuzz?: boolean;
  /** Authentication config for security fuzzing */
  authConfig?: AuthConfig;
}

export interface AuthConfig {
  loginUrl: string;
  credentials: Record<string, string>;
  submitSelector: string;
  successIndicator: string;
}

export interface DiffResult {
  newBugs: BugFinding[];
  fixedBugs: BugFinding[];
  regressions: BugFinding[];
  summary: string;
}

/**
 * Compare current scan against a baseline to find regressions and fixes.
 */
export function diffScans(current: ScanResult, baseline: ScanResult): DiffResult {
  const baselineIds = new Set(baseline.bugs.map((b) => b.id));
  const currentIds = new Set(current.bugs.map((b) => b.id));

  const newBugs = current.bugs.filter((b) => !baselineIds.has(b.id));
  const fixedBugs = baseline.bugs.filter((b) => !currentIds.has(b.id));

  // Regressions: bugs that were fixed but reappeared, or new critical/high bugs
  const regressions = newBugs.filter(
    (b) => b.severity === "critical" || b.severity === "high"
  );

  const summary = [
    `## 🐛 BugScout CI — Scan Diff`,
    "",
    `| Metric | Baseline | Current | Δ |`,
    `| ------ | -------- | ------- | - |`,
    `| Pages | ${baseline.stats.pagesCrawled} | ${current.stats.pagesCrawled} | ${current.stats.pagesCrawled - baseline.stats.pagesCrawled > 0 ? "+" : ""}${current.stats.pagesCrawled - baseline.stats.pagesCrawled} |`,
    `| Bugs | ${baseline.stats.bugsFound} | ${current.stats.bugsFound} | ${current.stats.bugsFound - baseline.stats.bugsFound > 0 ? "+" : ""}${current.stats.bugsFound - baseline.stats.bugsFound} |`,
    `| New bugs | — | ${newBugs.length} | — |`,
    `| Fixed bugs | — | ${fixedBugs.length} | — |`,
    `| Regressions | — | ${regressions.length} | — |`,
    "",
  ].join("\n");

  return { newBugs, fixedBugs, regressions, summary };
}

/**
 * Generate a GitHub Actions workflow YAML for BugScout.
 */
export function generateGithubActionWorkflow(): string {
  // Using array join to avoid TypeScript template-literal conflicts
  // with GitHub Actions \${{ }} syntax and embedded JS.
  const lines = [
    "# BugScout — Automated Web QA on PR Preview Deployments",
    "# Generated by bugscout ci --init",
    "",
    "name: BugScout QA Scan",
    "",
    "on:",
    "  pull_request:",
    "    types: [opened, synchronize, reopened]",
    "  deployment_status:",
    "    states: [success]",
    "",
    "jobs:",
    "  bugscout-scan:",
    "    runs-on: ubuntu-latest",
    "    if: ${{ github.event.deployment_status.state == 'success' || github.event_name == 'pull_request' }}",
    "    steps:",
    "      - uses: actions/checkout@v4",
    "",
    "      - name: Setup Node.js",
    "        uses: actions/setup-node@v4",
    "        with:",
    "          node-version: '22'",
    "          cache: 'npm'",
    "",
    "      - name: Install dependencies",
    "        run: npm ci",
    "",
    "      - name: Install Playwright browsers",
    "        run: npx playwright install chromium --with-deps",
    "",
    "      - name: Determine target URL",
    "        id: url",
    "        run: |",
    "          if [ -n \"$DEPLOY_URL\" ]; then",
    '            echo "target=$DEPLOY_URL" >> $GITHUB_OUTPUT',
    "          else",
    '            echo "target=${{ github.event.deployment_status.target_url || github.event.pull_request.html_url }}" >> $GITHUB_OUTPUT',
    "          fi",
    "",
    "      - name: Run BugScout",
    "        run: |",
    '          npx bugscout "${{ steps.url.outputs.target }}" \\',
    "            --output ./bugscout-results \\",
    "            --max-pages 30 \\",
    "            --timeout 20",
    "",
    "      - name: Upload report",
    "        uses: actions/upload-artifact@v4",
    "        with:",
    "          name: bugscout-report",
    "          path: ./bugscout-results/",
    "",
    "      - name: Comment PR",
    "        if: ${{ github.event_name == 'pull_request' }}",
    "        uses: actions/github-script@v7",
    "        with:",
    "          script: |",
    "            const fs = require('fs');",
    "            const report = fs.readFileSync('./bugscout-results/report.md', 'utf-8');",
    "            const summary = report.split('## \\u{1F4CA} Summary')[1]?.split('##')[0] || 'Scan complete.';",
    "            const body = '## \\u{1F41B} BugScout Scan Results\\n\\n' + summary +",
    "              '\\n\\n[\\u{1F4C4} Full report](' + process.env.GITHUB_SERVER_URL + '/' +",
    "              context.repo.owner + '/' + context.repo.repo + '/actions/runs/' + context.runId + ')';",
    "            await github.rest.issues.createComment({",
    "              owner: context.repo.owner,",
    "              repo: context.repo.repo,",
    "              issue_number: context.issue.number,",
    "              body",
    "            });",
    "",
  ];
  return lines.join("\n");
}

/**
 * Get a markdown summary suitable for a PR comment.
 */
export function prCommentSummary(result: ScanResult): string {
  const { stats, bugs } = result;
  const lines: string[] = [];

  lines.push("## 🐛 BugScout Scan Results");
  lines.push("");
  lines.push(
    `Scanned **${stats.pagesCrawled} pages** on \`${result.flowMap.baseUrl}\` and found **${stats.bugsFound} issues** (${(stats.durationMs / 1000).toFixed(1)}s).`
  );
  lines.push("");

  if (bugs.length === 0) {
    lines.push("✅ No bugs detected!");
    return lines.join("\n");
  }

  const crit = bugs.filter((b) => b.severity === "critical");
  const high = bugs.filter((b) => b.severity === "high");
  const med = bugs.filter((b) => b.severity === "medium");

  lines.push("### 🔴 Critical");
  for (const b of crit.slice(0, 5)) {
    lines.push(`- ${b.title} (${b.url})`);
  }
  if (crit.length === 0) lines.push("- None");

  lines.push("");
  lines.push("### 🟠 High");
  for (const b of high.slice(0, 5)) {
    lines.push(`- ${b.title}`);
  }
  if (high.length === 0) lines.push("- None");

  if (med.length > 0) {
    lines.push("");
    lines.push(`*+${med.length} medium-severity issues — see full report for details.*`);
  }

  lines.push("");
  const runUrl = typeof process !== "undefined" ? process.env["CI_RUN_URL"] || "#" : "#";
  lines.push(`📄 Full report available in the [CI run artifacts](${runUrl}).`);

  return lines.join("\n");
}

/**
 * Security fuzzing stub: authenticate and probe discovered endpoints for IDOR.
 * Only call this on targets you own or have explicit authorization to test.
 */
export async function securityFuzzStub(
  baseUrl: string,
  authConfig: AuthConfig,
  flows: string[]
): Promise<BugFinding[]> {
  // This is a deliberate stub — full implementation bridges to PentestAI patterns.
  // The architecture supports it; actual fuzzing requires per-target authorization.
  console.warn(
    "⚠️  Security fuzzing is a stub. Full implementation requires explicit target authorization."
  );
  console.warn(
    `    Would authenticate at ${authConfig.loginUrl}, then probe ${flows.length} discovered flows on ${baseUrl}.`
  );

  return [
    {
      id: "BUG-SEC-STUB",
      severity: "info",
      category: "other",
      title: "Security fuzzing not yet executed",
      description:
        "The security fuzzing extension is architecturally supported but requires explicit per-target authorization. This is a placeholder finding indicating the module is ready for authorized use.",
      url: baseUrl,
    },
  ];
}
